spring:
  application:
    name: discovery
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8001

